"""empty message

Revision ID: 221f55d86df4
Revises: fba98e530f34
Create Date: 2021-07-21 15:58:20.985898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221f55d86df4'
down_revision = 'fba98e530f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clinic', sa.Integer(), nullable=True),
    sa.Column('id_pet', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('avaliable', 'reserved', name='reservation_status'), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_doctor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_clinic'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_doctor'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pet'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
